var amdi18n = {
    "__root": {
        "ACCESSIBILITY": "Accessibility",
        "ACCESSIBILITY_INFORMATION_NOT_AVAILABLE": "Accessibility information not available",
        "ACCESSIBILITY_SCORE_HIGH": "Accessibility score: High",
        "ACCESSIBILITY_SCORE_LOW": "Accessibility score: Low",
        "ACCESSIBILITY_SCORE_MEDIUM": "Accessibility score: Medium",
        "ACCESSIBILITY_SCORE_PERCENT": "Accessibility score: {0}",
        "ACCESSIBILITY_SCORE_PERFECT": "Accessibility score: Perfect",
        "ACTIONS": "Actions",
        "ALTERNATIVE_FORMATS": "Alternative formats",
        "ATTO_BLOCK_QUOTED": "Quoted",
        "ATTO_BLOCK_HEADING_1": "Heading 1",
        "ATTO_BLOCK_HEADING_2": "Heading 2",
        "ATTO_BLOCK_HEADING_3": "Heading 3",
        "ATTO_BLOCK_PLAIN": "Plain",
        "ATTO_BLOCK_PRE": "Pre-formatted",
        "CANCEL": "Cancel",
        "CLICK_TO_IMPROVE": "Select to improve",
        "DOWNLOAD": "Download",
        "DOWNLOAD_ALTERNATIVE_FORMATS_ELLIPSIS": "Download alternative formats ...",
        "DOWNLOAD_OPTIONS": "Download options",
        "FILENAME_ALTERNATIVE_FORMAT": "{FILENAME} - Alternative Formats",
        "FILE_HAS_BEEN_DELETED": "File has been deleted",
        "FILE_TYPE_DOCUMENT": "Document",
        "FILE_TYPE_HTML_PAGE": "HTML file",
        "FILE_TYPE_IMAGE": "Image",
        "FILE_TYPE_OTHER": "Other",
        "FILE_TYPE_PDF": "PDF document",
        "FILE_TYPE_PRESENTATION": "Presentation",
        "FILE_TYPE_SCORE": "{0} - {1}",
        "FIX": "Fix",
        "INSTRUCTOR_FEEDBACK": "Instructor feedback",
        "INSTRUCTOR_FEEDBACK_FOR": "Instructor feedback for {0}",
        "LOADING_INSTRUCTOR_FEEDBACK_PLEASE_WAIT": "Loading Instructor Feedback. Please wait.",
        "POTENTIALLY_SEIZURE_INDUCING": "Potentially seizure inducing",
        "POTENTIALLY_SEIZURE_INDUCING_ANIMATION_PRESS_TO_ENABLE": "Potentially seizure inducing animation. Press to enable.",
        "PREVIEW": "Preview",
        "SHOW_IMAGE_ANYWAY": "Show image anyway",
        "X_OF_Y": "{0} / {1}"
    },
    "__ar": {
        "ACCESSIBILITY": "إمكانية وصول ذوي الاحتياجات الخاصة",
        "ACCESSIBILITY_INFORMATION_NOT_AVAILABLE": "معلومات إمكانية وصول ذوي الاحتياجات الخاصة غير متاحة",
        "ACCESSIBILITY_SCORE_HIGH": "درجة إمكانية وصول ذوي الاحتياجات الخاصة: عالية",
        "ACCESSIBILITY_SCORE_LOW": "درجة إمكانية وصول ذوي الاحتياجات الخاصة: منخفضة",
        "ACCESSIBILITY_SCORE_MEDIUM": "درجة إمكانية وصول ذوي الاحتياجات الخاصة: متوسطة",
        "ACCESSIBILITY_SCORE_PERCENT": "درجة إمكانية وصول ذوي الاحتياجات الخاصة: {0}",
        "ACCESSIBILITY_SCORE_PERFECT": "درجة إمكانية وصول ذوي الاحتياجات الخاصة: ممتازة",
        "ACTIONS": "الإجراءات",
        "ALTERNATIVE_FORMATS": "تنسيقات بديلة",
        "ATTO_BLOCK_QUOTED": "موضوع بين علامات اقتباس",
        "ATTO_BLOCK_HEADING_1": "العنوان 1",
        "ATTO_BLOCK_HEADING_2": "العنوان 2",
        "ATTO_BLOCK_HEADING_3": "العنوان 3",
        "ATTO_BLOCK_PLAIN": "عادي",
        "ATTO_BLOCK_PRE": "مُنسَّق مسبقًا",
        "CANCEL": "إلغاء الأمر",
        "CLICK_TO_IMPROVE": "التحديد للتحسين",
        "DOWNLOAD": "تنزيل",
        "DOWNLOAD_ALTERNATIVE_FORMATS_ELLIPSIS": "تنزيل تنسيقات بديلة ...",
        "DOWNLOAD_OPTIONS": "خيارات التنزيل",
        "FILENAME_ALTERNATIVE_FORMAT": "{FILENAME} - التنسيقات البديلة",
        "FILE_HAS_BEEN_DELETED": "تم حذف الملف",
        "FILE_TYPE_DOCUMENT": "المستند",
        "FILE_TYPE_HTML_PAGE": "ملف HTML",
        "FILE_TYPE_IMAGE": "الصورة",
        "FILE_TYPE_OTHER": "أخرى",
        "FILE_TYPE_PDF": "مستند PDF",
        "FILE_TYPE_PRESENTATION": "العرض التقديمي",
        "FILE_TYPE_SCORE": "{0} - {1}",
        "FIX": "إصلاح",
        "INSTRUCTOR_FEEDBACK": "ملاحظات المدرس",
        "INSTRUCTOR_FEEDBACK_FOR": "ملاحظات المدرس الخاصة بـ {0}",
        "LOADING_INSTRUCTOR_FEEDBACK_PLEASE_WAIT": "تحميل ملاحظات المدرس. يرجى الانتظار.",
        "POTENTIALLY_SEIZURE_INDUCING": "احتمال حدوث نوبة صرع",
        "POTENTIALLY_SEIZURE_INDUCING_ANIMATION_PRESS_TO_ENABLE": "احتمال حدوث نوبة صرع من الرسوم المتحركة. اضغط للتمكين.",
        "PREVIEW": "معاينة",
        "SHOW_IMAGE_ANYWAY": "إظهار الصورة على أي حال",
        "X_OF_Y": "{0} / {1}"
    },
    "__ca": {
        "ACCESSIBILITY": "Accessibilitat",
        "ACCESSIBILITY_INFORMATION_NOT_AVAILABLE": "Informació d'accessibilitat no disponible",
        "ACCESSIBILITY_SCORE_HIGH": "Puntuació d'accessibilitat: alta",
        "ACCESSIBILITY_SCORE_LOW": "Puntuació d'accessibilitat: baixa",
        "ACCESSIBILITY_SCORE_MEDIUM": "Puntuació d'accessibilitat: mitjana",
        "ACCESSIBILITY_SCORE_PERCENT": "Puntuació d'accessibilitat: {0}",
        "ACCESSIBILITY_SCORE_PERFECT": "Puntuació d'accessibilitat: perfecta",
        "ACTIONS": "Accions",
        "ALTERNATIVE_FORMATS": "Formats alternatius",
        "ATTO_BLOCK_QUOTED": "Entre cometes",
        "ATTO_BLOCK_HEADING_1": "Títol 1",
        "ATTO_BLOCK_HEADING_2": "Títol 2",
        "ATTO_BLOCK_HEADING_3": "Títol 3",
        "ATTO_BLOCK_PLAIN": "Sense format",
        "ATTO_BLOCK_PRE": "Formatat prèviament",
        "CANCEL": "Cancel·la",
        "CLICK_TO_IMPROVE": "Seleccioneu per millorar",
        "DOWNLOAD": "Descarrega",
        "DOWNLOAD_ALTERNATIVE_FORMATS_ELLIPSIS": "Descarrega formats alternatius...",
        "DOWNLOAD_OPTIONS": "Opcions de descàrrega",
        "FILENAME_ALTERNATIVE_FORMAT": "{FILENAME} - Formats alternatius",
        "FILE_HAS_BEEN_DELETED": "S'ha suprimit el fitxer",
        "FILE_TYPE_DOCUMENT": "Document",
        "FILE_TYPE_HTML_PAGE": "Fitxer HTML",
        "FILE_TYPE_IMAGE": "Imatge",
        "FILE_TYPE_OTHER": "Altres",
        "FILE_TYPE_PDF": "Document PDF",
        "FILE_TYPE_PRESENTATION": "Presentació",
        "FILE_TYPE_SCORE": "{0} - {1}",
        "FIX": "Corregeix",
        "INSTRUCTOR_FEEDBACK": "Comentaris de l'instructor",
        "INSTRUCTOR_FEEDBACK_FOR": "Comentaris de l'instructor per a {0}",
        "LOADING_INSTRUCTOR_FEEDBACK_PLEASE_WAIT": "S'estan carregant els comentaris de l'instructor. Espereu.",
        "POTENTIALLY_SEIZURE_INDUCING": "Pot provocar atacs",
        "POTENTIALLY_SEIZURE_INDUCING_ANIMATION_PRESS_TO_ENABLE": "Aquesta animació podria provocar atacs. Premeu per activar-la.",
        "PREVIEW": "Visualització prèvia",
        "SHOW_IMAGE_ANYWAY": "Mostra la imatge de totes maneres",
        "X_OF_Y": "{0} / {1}"
    },
    "__cy": {
        "ACCESSIBILITY": "Hygyrchedd",
        "ACCESSIBILITY_INFORMATION_NOT_AVAILABLE": "Gwybodaeth hygyrchedd ddim ar gael",
        "ACCESSIBILITY_SCORE_HIGH": "Sgôr hygyrchedd: Uchel",
        "ACCESSIBILITY_SCORE_LOW": "Sgôr hygyrchedd: Isel",
        "ACCESSIBILITY_SCORE_MEDIUM": "Sgôr hygyrchedd: Canolig",
        "ACCESSIBILITY_SCORE_PERCENT": "Sgôr hygyrchedd: {0}",
        "ACCESSIBILITY_SCORE_PERFECT": "Sgôr hygyrchedd: Perffaith",
        "ACTIONS": "Gweithrediadau",
        "ALTERNATIVE_FORMATS": "Fformatau amgen",
        "ATTO_BLOCK_QUOTED": "Dyfynnwyd",
        "ATTO_BLOCK_HEADING_1": "Pennawd 1",
        "ATTO_BLOCK_HEADING_2": "Pennawd 2",
        "ATTO_BLOCK_HEADING_3": "Pennawd 3",
        "ATTO_BLOCK_PLAIN": "Plaen",
        "ATTO_BLOCK_PRE": "Rhagfformatiwyd",
        "CANCEL": "Canslo",
        "CLICK_TO_IMPROVE": "Dewiswch i'w wella",
        "DOWNLOAD": "Lawrlwytho",
        "DOWNLOAD_ALTERNATIVE_FORMATS_ELLIPSIS": "Lawrlwytho fformatau amgen ...",
        "DOWNLOAD_OPTIONS": "Opsiynau lawrlwytho",
        "FILENAME_ALTERNATIVE_FORMAT": "{FILENAME} - Fformatau Amgen",
        "FILE_HAS_BEEN_DELETED": "Dilëwyd y ffeil",
        "FILE_TYPE_DOCUMENT": "Dogfen",
        "FILE_TYPE_HTML_PAGE": "Ffeil HTML",
        "FILE_TYPE_IMAGE": "Delwedd",
        "FILE_TYPE_OTHER": "Arall",
        "FILE_TYPE_PDF": "Dogfen PDF",
        "FILE_TYPE_PRESENTATION": "Cyflwyniad",
        "FILE_TYPE_SCORE": "{0} - {1}",
        "FIX": "Trwsio",
        "INSTRUCTOR_FEEDBACK": "Adborth gan yr hyfforddwr",
        "INSTRUCTOR_FEEDBACK_FOR": "Adborth hyfforddwr ar gyfer {0}",
        "LOADING_INSTRUCTOR_FEEDBACK_PLEASE_WAIT": "Wrthi'n llwytho adborth yr hyfforddwr. Arhoswch.",
        "POTENTIALLY_SEIZURE_INDUCING": "Gallai achosi trawiad",
        "POTENTIALLY_SEIZURE_INDUCING_ANIMATION_PRESS_TO_ENABLE": "Animeiddiad a allai achosi trawiad. Pwyswch i'w alluogi.",
        "PREVIEW": "Rhagolwg",
        "SHOW_IMAGE_ANYWAY": "Dangos y ddelwedd beth bynnag",
        "X_OF_Y": "{0} / {1}"
    },
    "__da": {
        "ACCESSIBILITY": "Tilgængelighed",
        "ACCESSIBILITY_INFORMATION_NOT_AVAILABLE": "Ingen oplysninger om tilgængelighed",
        "ACCESSIBILITY_SCORE_HIGH": "Tilgængelighedsvurdering: Høj",
        "ACCESSIBILITY_SCORE_LOW": "Tilgængelighedsvurdering: Lav",
        "ACCESSIBILITY_SCORE_MEDIUM": "Tilgængelighedsvurdering: Middel",
        "ACCESSIBILITY_SCORE_PERCENT": "Tilgængelighedsvurdering: {0}",
        "ACCESSIBILITY_SCORE_PERFECT": "Tilgængelighedsvurdering: Perfekt",
        "ACTIONS": "Handlinger",
        "ALTERNATIVE_FORMATS": "Alternative formater",
        "ATTO_BLOCK_QUOTED": "Citeret",
        "ATTO_BLOCK_HEADING_1": "Overskrift 1",
        "ATTO_BLOCK_HEADING_2": "Overskrift 2",
        "ATTO_BLOCK_HEADING_3": "Overskrift 3",
        "ATTO_BLOCK_PLAIN": "Almindelig",
        "ATTO_BLOCK_PRE": "Forhåndsformateret",
        "CANCEL": "Annuller",
        "CLICK_TO_IMPROVE": "Vælg for at forbedre",
        "DOWNLOAD": "Download",
        "DOWNLOAD_ALTERNATIVE_FORMATS_ELLIPSIS": "Download alternative formater ...",
        "DOWNLOAD_OPTIONS": "Indstillinger for download",
        "FILENAME_ALTERNATIVE_FORMAT": "{FILENAME} - Alternative formater",
        "FILE_HAS_BEEN_DELETED": "Filen blev slettet",
        "FILE_TYPE_DOCUMENT": "Dokument",
        "FILE_TYPE_HTML_PAGE": "HTML-fil",
        "FILE_TYPE_IMAGE": "Billede",
        "FILE_TYPE_OTHER": "Andet",
        "FILE_TYPE_PDF": "PDF-dokument",
        "FILE_TYPE_PRESENTATION": "Præsentation",
        "FILE_TYPE_SCORE": "{0} - {1}",
        "FIX": "Ret",
        "INSTRUCTOR_FEEDBACK": "Undervisers feedback",
        "INSTRUCTOR_FEEDBACK_FOR": "Undervisers feedback for {0}",
        "LOADING_INSTRUCTOR_FEEDBACK_PLEASE_WAIT": "Indlæser undervisers feedback. Vent venligst.",
        "POTENTIALLY_SEIZURE_INDUCING": "Kan fremkalde epileptiske anfald",
        "POTENTIALLY_SEIZURE_INDUCING_ANIMATION_PRESS_TO_ENABLE": "Animationen kan fremkalde epileptiske anfald. Tryk for at aktivere.",
        "PREVIEW": "Eksempelvisning",
        "SHOW_IMAGE_ANYWAY": "Vis billedet alligevel",
        "X_OF_Y": "{0}/{1}"
    },
    "__de": {
        "ACCESSIBILITY": "Zugänglichkeit",
        "ACCESSIBILITY_INFORMATION_NOT_AVAILABLE": "Informationen zur Zugänglichkeit nicht verfügbar",
        "ACCESSIBILITY_SCORE_HIGH": "Zugänglichkeit: Hoch",
        "ACCESSIBILITY_SCORE_LOW": "Zugänglichkeit: Gering",
        "ACCESSIBILITY_SCORE_MEDIUM": "Zugänglichkeit: Mittel",
        "ACCESSIBILITY_SCORE_PERCENT": "Bewertung der Zugänglichkeit: {0}",
        "ACCESSIBILITY_SCORE_PERFECT": "Zugänglichkeit: Perfekt",
        "ACTIONS": "Aktionen",
        "ALTERNATIVE_FORMATS": "Alternative Formate",
        "ATTO_BLOCK_QUOTED": "Zitiert",
        "ATTO_BLOCK_HEADING_1": "Überschrift 1",
        "ATTO_BLOCK_HEADING_2": "Überschrift 2",
        "ATTO_BLOCK_HEADING_3": "Überschrift 3",
        "ATTO_BLOCK_PLAIN": "Einfach",
        "ATTO_BLOCK_PRE": "Vorformatiert",
        "CANCEL": "Abbrechen",
        "CLICK_TO_IMPROVE": "Zum Verbessern auswählen",
        "DOWNLOAD": "Herunterladen",
        "DOWNLOAD_ALTERNATIVE_FORMATS_ELLIPSIS": "Alternative Formate herunterladen ...",
        "DOWNLOAD_OPTIONS": "Optionen zum Herunterladen",
        "FILENAME_ALTERNATIVE_FORMAT": "{FILENAME} – Alternative Formate",
        "FILE_HAS_BEEN_DELETED": "Datei wurde gelöscht",
        "FILE_TYPE_DOCUMENT": "Dokument",
        "FILE_TYPE_HTML_PAGE": "HTML-Datei",
        "FILE_TYPE_IMAGE": "Grafik",
        "FILE_TYPE_OTHER": "Andere",
        "FILE_TYPE_PDF": "PDF-Dokument",
        "FILE_TYPE_PRESENTATION": "Präsentation",
        "FILE_TYPE_SCORE": "{0} - {1}",
        "FIX": "Beheben",
        "INSTRUCTOR_FEEDBACK": "Feedback des Kursleiters",
        "INSTRUCTOR_FEEDBACK_FOR": "Feedback des Kursleiters für {0}",
        "LOADING_INSTRUCTOR_FEEDBACK_PLEASE_WAIT": "Feedback des Kursleiters wird geladen. Bitte warten.",
        "POTENTIALLY_SEIZURE_INDUCING": "Kann Anfälle auslösen",
        "POTENTIALLY_SEIZURE_INDUCING_ANIMATION_PRESS_TO_ENABLE": "Animation kann Anfälle auslösen. Zum Aktivieren drücken.",
        "PREVIEW": "Vorschau",
        "SHOW_IMAGE_ANYWAY": "Grafik dennoch anzeigen",
        "X_OF_Y": "{0}/{1}"
    },
    "__en-gb": {
        "ACCESSIBILITY": "Accessibility",
        "ACCESSIBILITY_INFORMATION_NOT_AVAILABLE": "Accessibility information not available",
        "ACCESSIBILITY_SCORE_HIGH": "Accessibility score: High",
        "ACCESSIBILITY_SCORE_LOW": "Accessibility score: Low",
        "ACCESSIBILITY_SCORE_MEDIUM": "Accessibility score: Medium",
        "ACCESSIBILITY_SCORE_PERCENT": "Accessibility score: {0}",
        "ACCESSIBILITY_SCORE_PERFECT": "Accessibility score: Perfect",
        "ACTIONS": "Actions",
        "ALTERNATIVE_FORMATS": "Alternative formats",
        "ATTO_BLOCK_QUOTED": "Quoted",
        "ATTO_BLOCK_HEADING_1": "Heading 1",
        "ATTO_BLOCK_HEADING_2": "Heading 2",
        "ATTO_BLOCK_HEADING_3": "Heading 3",
        "ATTO_BLOCK_PLAIN": "Plain",
        "ATTO_BLOCK_PRE": "Pre-formatted",
        "CANCEL": "Cancel",
        "CLICK_TO_IMPROVE": "Select to improve",
        "DOWNLOAD": "Download",
        "DOWNLOAD_ALTERNATIVE_FORMATS_ELLIPSIS": "Download alternative formats ...",
        "DOWNLOAD_OPTIONS": "Download options",
        "FILENAME_ALTERNATIVE_FORMAT": "{FILENAME} - Alternative Formats",
        "FILE_HAS_BEEN_DELETED": "File has been deleted",
        "FILE_TYPE_DOCUMENT": "Document",
        "FILE_TYPE_HTML_PAGE": "HTML file",
        "FILE_TYPE_IMAGE": "Image",
        "FILE_TYPE_OTHER": "Other",
        "FILE_TYPE_PDF": "PDF document",
        "FILE_TYPE_PRESENTATION": "Presentation",
        "FILE_TYPE_SCORE": "{0} - {1}",
        "FIX": "Fix",
        "INSTRUCTOR_FEEDBACK": "Instructor feedback",
        "INSTRUCTOR_FEEDBACK_FOR": "Instructor feedback for {0}",
        "LOADING_INSTRUCTOR_FEEDBACK_PLEASE_WAIT": "Loading Instructor Feedback. Please wait.",
        "POTENTIALLY_SEIZURE_INDUCING": "Potentially seizure-inducing",
        "POTENTIALLY_SEIZURE_INDUCING_ANIMATION_PRESS_TO_ENABLE": "Potentially seizure-inducing animation. Press to enable.",
        "PREVIEW": "Preview",
        "SHOW_IMAGE_ANYWAY": "Show image anyway",
        "X_OF_Y": "{0} / {1}"
    },
    "__en-us-pro": {
        "ACCESSIBILITY": "Accessibility",
        "ACCESSIBILITY_INFORMATION_NOT_AVAILABLE": "Accessibility information not available",
        "ACCESSIBILITY_SCORE_HIGH": "Accessibility score: High",
        "ACCESSIBILITY_SCORE_LOW": "Accessibility score: Low",
        "ACCESSIBILITY_SCORE_MEDIUM": "Accessibility score: Medium",
        "ACCESSIBILITY_SCORE_PERCENT": "Accessibility score: {0}",
        "ACCESSIBILITY_SCORE_PERFECT": "Accessibility score: Perfect",
        "ACTIONS": "Actions",
        "ALTERNATIVE_FORMATS": "Alternative formats",
        "ATTO_BLOCK_QUOTED": "Quoted",
        "ATTO_BLOCK_HEADING_1": "Heading 1",
        "ATTO_BLOCK_HEADING_2": "Heading 2",
        "ATTO_BLOCK_HEADING_3": "Heading 3",
        "ATTO_BLOCK_PLAIN": "Plain",
        "ATTO_BLOCK_PRE": "Pre-formatted",
        "CANCEL": "Cancel",
        "CLICK_TO_IMPROVE": "Select to improve",
        "DOWNLOAD": "Download",
        "DOWNLOAD_ALTERNATIVE_FORMATS_ELLIPSIS": "Download alternative formats ...",
        "DOWNLOAD_OPTIONS": "Download options",
        "FILENAME_ALTERNATIVE_FORMAT": "{FILENAME} - Alternative Formats",
        "FILE_HAS_BEEN_DELETED": "File has been deleted",
        "FILE_TYPE_DOCUMENT": "Document",
        "FILE_TYPE_HTML_PAGE": "HTML file",
        "FILE_TYPE_IMAGE": "Image",
        "FILE_TYPE_OTHER": "Other",
        "FILE_TYPE_PDF": "PDF document",
        "FILE_TYPE_PRESENTATION": "Presentation",
        "FILE_TYPE_SCORE": "{0} - {1}",
        "FIX": "Fix",
        "INSTRUCTOR_FEEDBACK": "Instructor feedback",
        "INSTRUCTOR_FEEDBACK_FOR": "Instructor feedback for {0}",
        "LOADING_INSTRUCTOR_FEEDBACK_PLEASE_WAIT": "Loading Instructor Feedback. Please wait.",
        "POTENTIALLY_SEIZURE_INDUCING": "Potentially seizure inducing",
        "POTENTIALLY_SEIZURE_INDUCING_ANIMATION_PRESS_TO_ENABLE": "Potentially seizure inducing animation. Press to enable.",
        "PREVIEW": "Preview",
        "SHOW_IMAGE_ANYWAY": "Show image anyway",
        "X_OF_Y": "{0} / {1}"
    },
    "__es": {
        "ACCESSIBILITY": "Accesibilidad",
        "ACCESSIBILITY_INFORMATION_NOT_AVAILABLE": "Información de accesibilidad no disponible",
        "ACCESSIBILITY_SCORE_HIGH": "Calificación de accesibilidad: alta",
        "ACCESSIBILITY_SCORE_LOW": "Calificación de accesibilidad: baja",
        "ACCESSIBILITY_SCORE_MEDIUM": "Calificación de accesibilidad: media",
        "ACCESSIBILITY_SCORE_PERCENT": "Puntuación de accesibilidad: {0}",
        "ACCESSIBILITY_SCORE_PERFECT": "Calificación de accesibilidad: perfecta",
        "ACTIONS": "Acciones",
        "ALTERNATIVE_FORMATS": "Formatos alternativos",
        "ATTO_BLOCK_QUOTED": "Citado",
        "ATTO_BLOCK_HEADING_1": "Encabezado 1",
        "ATTO_BLOCK_HEADING_2": "Encabezado 2",
        "ATTO_BLOCK_HEADING_3": "Encabezado 3",
        "ATTO_BLOCK_PLAIN": "Solo texto",
        "ATTO_BLOCK_PRE": "Preformateado",
        "CANCEL": "Cancelar",
        "CLICK_TO_IMPROVE": "Seleccione para mejorar",
        "DOWNLOAD": "Descargar",
        "DOWNLOAD_ALTERNATIVE_FORMATS_ELLIPSIS": "Descargar formatos alternativos...",
        "DOWNLOAD_OPTIONS": "Opciones de descarga",
        "FILENAME_ALTERNATIVE_FORMAT": "{FILENAME}: formatos alternativos",
        "FILE_HAS_BEEN_DELETED": "Se eliminó el archivo",
        "FILE_TYPE_DOCUMENT": "Documento",
        "FILE_TYPE_HTML_PAGE": "Archivo HTML",
        "FILE_TYPE_IMAGE": "Imagen",
        "FILE_TYPE_OTHER": "Otros",
        "FILE_TYPE_PDF": "Documento PDF",
        "FILE_TYPE_PRESENTATION": "Presentación",
        "FILE_TYPE_SCORE": "{0}-{1}",
        "FIX": "Corregir",
        "INSTRUCTOR_FEEDBACK": "Comentarios del profesor",
        "INSTRUCTOR_FEEDBACK_FOR": "Comentarios del profesor para {0}",
        "LOADING_INSTRUCTOR_FEEDBACK_PLEASE_WAIT": "Cargando los comentarios del profesor. Aguarde un momento.",
        "POTENTIALLY_SEIZURE_INDUCING": "Puede generar convulsiones",
        "POTENTIALLY_SEIZURE_INDUCING_ANIMATION_PRESS_TO_ENABLE": "La animación puede generar convulsiones. Presione para permitir.",
        "PREVIEW": "Vista previa",
        "SHOW_IMAGE_ANYWAY": "Mostrar imagen de todas formas",
        "X_OF_Y": "{0} / {1}"
    },
    "__eu_ES": {
        "ACCESSIBILITY": "Irisgarritasuna",
        "ACCESSIBILITY_INFORMATION_NOT_AVAILABLE": "Irisgarritasun-informazioa ez dago eskuragarri",
        "ACCESSIBILITY_SCORE_HIGH": "Irisgarritasun-puntuazioa: altua",
        "ACCESSIBILITY_SCORE_LOW": "Irisgarritasun-puntuazioa: baxua",
        "ACCESSIBILITY_SCORE_MEDIUM": "Irisgarritasun-puntuazioa: ertaina",
        "ACCESSIBILITY_SCORE_PERCENT": "Irisgarritasun-puntuazioa: {0}",
        "ACCESSIBILITY_SCORE_PERFECT": "Irisgarritasun-puntuazioa: bikaina",
        "ACTIONS": "Ekintzak",
        "ALTERNATIVE_FORMATS": "Formatu alternatiboak",
        "ATTO_BLOCK_QUOTED": "Aipatuta",
        "ATTO_BLOCK_HEADING_1": "1. goiburukoa",
        "ATTO_BLOCK_HEADING_2": "2. goiburukoa",
        "ATTO_BLOCK_HEADING_3": "3. goiburukoa",
        "ATTO_BLOCK_PLAIN": "Soila",
        "ATTO_BLOCK_PRE": "Formatua aurrez emanda",
        "CANCEL": "Utzi",
        "CLICK_TO_IMPROVE": "Hautatu hobetzeko",
        "DOWNLOAD": "Deskargatu",
        "DOWNLOAD_ALTERNATIVE_FORMATS_ELLIPSIS": "Deskargatu formatu alternatiboak ...",
        "DOWNLOAD_OPTIONS": "Deskargatu aukerak",
        "FILENAME_ALTERNATIVE_FORMAT": "{FILENAME} - Formatu alternatiboak",
        "FILE_HAS_BEEN_DELETED": "Fitxategia ezabatu da",
        "FILE_TYPE_DOCUMENT": "Dokumentua",
        "FILE_TYPE_HTML_PAGE": "HTML fitxategia",
        "FILE_TYPE_IMAGE": "Irudia",
        "FILE_TYPE_OTHER": "Beste bat",
        "FILE_TYPE_PDF": "PDF dokumentua",
        "FILE_TYPE_PRESENTATION": "Aurkezpena",
        "FILE_TYPE_SCORE": "{0} - {1}",
        "FIX": "Konpondu",
        "INSTRUCTOR_FEEDBACK": "Irakaslearen iruzkinak",
        "INSTRUCTOR_FEEDBACK_FOR": "Irakaslearen iruzkinak {0}(r)i dagokionez",
        "LOADING_INSTRUCTOR_FEEDBACK_PLEASE_WAIT": "Irakaslearen iruzkinak kargatzen. Itxaron.",
        "POTENTIALLY_SEIZURE_INDUCING": "Baliteke konbultsioak eragitea",
        "POTENTIALLY_SEIZURE_INDUCING_ANIMATION_PRESS_TO_ENABLE": "Konbultsioak eragin ditzakeen animazioa. Sakatu hura gaitzeko.",
        "PREVIEW": "Aurrebista",
        "SHOW_IMAGE_ANYWAY": "Erakutsi irudia hala ere",
        "X_OF_Y": "{0} / {1}"
    },
    "__fi": {
        "ACCESSIBILITY": "Helppokäyttöisyys",
        "ACCESSIBILITY_INFORMATION_NOT_AVAILABLE": "Helppokäyttöisyystiedot eivät ole käytettävissä",
        "ACCESSIBILITY_SCORE_HIGH": "Helppokäyttöisyysarvo: korkea",
        "ACCESSIBILITY_SCORE_LOW": "Helppokäyttöisyysarvo: matala",
        "ACCESSIBILITY_SCORE_MEDIUM": "Helppokäyttöisyysarvo: keskitaso",
        "ACCESSIBILITY_SCORE_PERCENT": "Helppokäyttöisyysarvo: {0}",
        "ACCESSIBILITY_SCORE_PERFECT": "Helppokäyttöisyysarvo: täydellinen",
        "ACTIONS": "Toiminnot",
        "ALTERNATIVE_FORMATS": "Vaihtoehtoiset muodot",
        "ATTO_BLOCK_QUOTED": "Lainattu",
        "ATTO_BLOCK_HEADING_1": "Otsikko 1",
        "ATTO_BLOCK_HEADING_2": "Otsikko 2",
        "ATTO_BLOCK_HEADING_3": "Otsikko 3",
        "ATTO_BLOCK_PLAIN": "Tavallinen",
        "ATTO_BLOCK_PRE": "Esimuotoiltu",
        "CANCEL": "Peruuta",
        "CLICK_TO_IMPROVE": "Paranna valitsemalla",
        "DOWNLOAD": "Lataa",
        "DOWNLOAD_ALTERNATIVE_FORMATS_ELLIPSIS": "Lataa vaihtoehtoiset muodot...",
        "DOWNLOAD_OPTIONS": "Latausasetukset",
        "FILENAME_ALTERNATIVE_FORMAT": "{FILENAME} - Vaihtoehtoiset tiedostomuodot",
        "FILE_HAS_BEEN_DELETED": "Tiedosto on poistettu",
        "FILE_TYPE_DOCUMENT": "Asiakirja",
        "FILE_TYPE_HTML_PAGE": "HTML-tiedosto",
        "FILE_TYPE_IMAGE": "Kuva",
        "FILE_TYPE_OTHER": "Muu",
        "FILE_TYPE_PDF": "PDF-asiakirja",
        "FILE_TYPE_PRESENTATION": "Esitys",
        "FILE_TYPE_SCORE": "{0}–{1}",
        "FIX": "Korjaa",
        "INSTRUCTOR_FEEDBACK": "Ohjaajan palaute",
        "INSTRUCTOR_FEEDBACK_FOR": "Ohjaajan palaute kohteelle {0}",
        "LOADING_INSTRUCTOR_FEEDBACK_PLEASE_WAIT": "Ladataan ohjaajan palautetta. Odota.",
        "POTENTIALLY_SEIZURE_INDUCING": "Voi aiheuttaa epileptisiä kohtauksia",
        "POTENTIALLY_SEIZURE_INDUCING_ANIMATION_PRESS_TO_ENABLE": "Animaatio voi aiheuttaa epileptisiä kohtauksia. Ota käyttöön painamalla tätä.",
        "PREVIEW": "Esikatsele",
        "SHOW_IMAGE_ANYWAY": "Näytä kuva tästä huolimatta",
        "X_OF_Y": "{0} / {1}"
    },
    "__fr": {
        "ACCESSIBILITY": "Accessibilité",
        "ACCESSIBILITY_INFORMATION_NOT_AVAILABLE": "Les informations sur l'accessibilité ne sont pas disponibles",
        "ACCESSIBILITY_SCORE_HIGH": "Résultat d'accessibilité : élevé",
        "ACCESSIBILITY_SCORE_LOW": "Résultat d'accessibilité : faible",
        "ACCESSIBILITY_SCORE_MEDIUM": "Résultat d'accessibilité : moyen",
        "ACCESSIBILITY_SCORE_PERCENT": "Résultat d'accessibilité : {0}",
        "ACCESSIBILITY_SCORE_PERFECT": "Résultat d'accessibilité : parfait",
        "ACTIONS": "Actions",
        "ALTERNATIVE_FORMATS": "Formats alternatifs",
        "ATTO_BLOCK_QUOTED": "Citation",
        "ATTO_BLOCK_HEADING_1": "Titre 1",
        "ATTO_BLOCK_HEADING_2": "Titre 2",
        "ATTO_BLOCK_HEADING_3": "Titre 3",
        "ATTO_BLOCK_PLAIN": "Texte brut",
        "ATTO_BLOCK_PRE": "Pré-formaté",
        "CANCEL": "Annuler",
        "CLICK_TO_IMPROVE": "Sélectionnez pour améliorer",
        "DOWNLOAD": "Télécharger",
        "DOWNLOAD_ALTERNATIVE_FORMATS_ELLIPSIS": "Télécharger des formats alternatifs…",
        "DOWNLOAD_OPTIONS": "Options de téléchargement",
        "FILENAME_ALTERNATIVE_FORMAT": "{FILENAME} - Formats alternatifs",
        "FILE_HAS_BEEN_DELETED": "Le fichier a été supprimé",
        "FILE_TYPE_DOCUMENT": "Document",
        "FILE_TYPE_HTML_PAGE": "Fichier HTML",
        "FILE_TYPE_IMAGE": "Image",
        "FILE_TYPE_OTHER": "Autre",
        "FILE_TYPE_PDF": "Document PDF",
        "FILE_TYPE_PRESENTATION": "Présentation",
        "FILE_TYPE_SCORE": "{0} - {1}",
        "FIX": "Résoudre",
        "INSTRUCTOR_FEEDBACK": "Feed-back du professeur",
        "INSTRUCTOR_FEEDBACK_FOR": "Feed-back du professeur pour {0}",
        "LOADING_INSTRUCTOR_FEEDBACK_PLEASE_WAIT": "Chargement du feed-back du professeur en cours. Veuillez patienter.",
        "POTENTIALLY_SEIZURE_INDUCING": "Risque potentiel de crise d'épilepsie",
        "POTENTIALLY_SEIZURE_INDUCING_ANIMATION_PRESS_TO_ENABLE": "Animation susceptible de provoquer une crise d'épilepsie. Appuyez pour activer.",
        "PREVIEW": "Aperçu",
        "SHOW_IMAGE_ANYWAY": "Afficher quand même l'image",
        "X_OF_Y": "{0} / {1}"
    },
    "__fr-ca": {
        "ACCESSIBILITY": "Accessibilité",
        "ACCESSIBILITY_INFORMATION_NOT_AVAILABLE": "L'information d'accessibilité n'est pas disponible",
        "ACCESSIBILITY_SCORE_HIGH": "Score d'accessibilité : Élevé",
        "ACCESSIBILITY_SCORE_LOW": "Score d'accessibilité : Bas",
        "ACCESSIBILITY_SCORE_MEDIUM": "Score d'accessibilité : Moyen",
        "ACCESSIBILITY_SCORE_PERCENT": "Score d'accessibilité : {0}",
        "ACCESSIBILITY_SCORE_PERFECT": "Score d'accessibilité : Parfait",
        "ACTIONS": "Actions",
        "ALTERNATIVE_FORMATS": "Médias adaptés",
        "ATTO_BLOCK_QUOTED": "Citation",
        "ATTO_BLOCK_HEADING_1": "Titre 1",
        "ATTO_BLOCK_HEADING_2": "Titre 2",
        "ATTO_BLOCK_HEADING_3": "Titre 3",
        "ATTO_BLOCK_PLAIN": "Texte brut",
        "ATTO_BLOCK_PRE": "Pré-formaté",
        "CANCEL": "Annuler",
        "CLICK_TO_IMPROVE": "Sélectionner pour améliorer",
        "DOWNLOAD": "Télécharger",
        "DOWNLOAD_ALTERNATIVE_FORMATS_ELLIPSIS": "Télécharger d'autres formats...",
        "DOWNLOAD_OPTIONS": "Télécharger les options",
        "FILENAME_ALTERNATIVE_FORMAT": "{FILENAME} - Autres formats",
        "FILE_HAS_BEEN_DELETED": "Le fichier a été supprimé",
        "FILE_TYPE_DOCUMENT": "Document",
        "FILE_TYPE_HTML_PAGE": "Fichier HTML",
        "FILE_TYPE_IMAGE": "Image",
        "FILE_TYPE_OTHER": "Autre",
        "FILE_TYPE_PDF": "Document PDF",
        "FILE_TYPE_PRESENTATION": "Présentation",
        "FILE_TYPE_SCORE": "{0} - {1}",
        "FIX": "Corriger",
        "INSTRUCTOR_FEEDBACK": "Rétroactions de l'instructeur",
        "INSTRUCTOR_FEEDBACK_FOR": "Rétroactions de l'instructeur pour {0}",
        "LOADING_INSTRUCTOR_FEEDBACK_PLEASE_WAIT": "Chargement des rétroactions de l'instructeur en cours. Veuillez patienter.",
        "POTENTIALLY_SEIZURE_INDUCING": "Susceptible de provoquer une crise épileptique",
        "POTENTIALLY_SEIZURE_INDUCING_ANIMATION_PRESS_TO_ENABLE": "Cette animation est susceptible de provoquer une crise épileptique. Appuyez pour la lancer.",
        "PREVIEW": "Aperçu",
        "SHOW_IMAGE_ANYWAY": "Afficher l'image quand même",
        "X_OF_Y": "{0}/{1}"
    },
    "__ga": {
        "ACCESSIBILITY": "Inroctaineacht",
        "ACCESSIBILITY_INFORMATION_NOT_AVAILABLE": "Níl eolas inrochtaineachta ar fáil",
        "ACCESSIBILITY_SCORE_HIGH": "Inrochtaineacht scór: Ard",
        "ACCESSIBILITY_SCORE_LOW": "Inrochtaineacht scór: Íseal",
        "ACCESSIBILITY_SCORE_MEDIUM": "Inrochtaineacht scór: Meán",
        "ACCESSIBILITY_SCORE_PERCENT": "Scór inrochtaineachta: {0}",
        "ACCESSIBILITY_SCORE_PERFECT": "Inrochtaineacht scór: Foirfe",
        "ACTIONS": "Gníomhaíochtaí",
        "ALTERNATIVE_FORMATS": "Forméidí eile",
        "ATTO_BLOCK_QUOTED": "Luaite",
        "ATTO_BLOCK_HEADING_1": "Ceannteideal 1",
        "ATTO_BLOCK_HEADING_2": "Ceannteideal 2",
        "ATTO_BLOCK_HEADING_3": "Ceannteideal 3",
        "ATTO_BLOCK_PLAIN": "Simplí",
        "ATTO_BLOCK_PRE": "Réamhfhormáidithe",
        "CANCEL": "Cealaigh",
        "CLICK_TO_IMPROVE": "Roghnaigh chun feabhsú",
        "DOWNLOAD": "Íoslódáil",
        "DOWNLOAD_ALTERNATIVE_FORMATS_ELLIPSIS": "Íoslódáil formáidí malartacha",
        "DOWNLOAD_OPTIONS": "Roghanna íoslodáil",
        "FILENAME_ALTERNATIVE_FORMAT": "{FILENAME} - Formáidí Malartacha",
        "FILE_HAS_BEEN_DELETED": "Scriosadh an comhad",
        "FILE_TYPE_DOCUMENT": "Doiciméad",
        "FILE_TYPE_HTML_PAGE": "Comhad HTML",
        "FILE_TYPE_IMAGE": "Íomhá",
        "FILE_TYPE_OTHER": "Eile",
        "FILE_TYPE_PDF": "PDF doiciméid",
        "FILE_TYPE_PRESENTATION": "Láithreoireacht",
        "FILE_TYPE_SCORE": "{0} - {1}",
        "FIX": "Deisigh",
        "INSTRUCTOR_FEEDBACK": "Aiseolas ó theagascóirí",
        "INSTRUCTOR_FEEDBACK_FOR": "Aiseolas teagascóra do {0}",
        "LOADING_INSTRUCTOR_FEEDBACK_PLEASE_WAIT": "Aiseolas do Theagascóirí ag lódáil. Fán le do thoil.",
        "POTENTIALLY_SEIZURE_INDUCING": "D'fhéadfadh sé seo taom a spreagadh",
        "POTENTIALLY_SEIZURE_INDUCING_ANIMATION_PRESS_TO_ENABLE": "Beochan a d’fhéadfadh urghabháil a dhéanamh. Brúigh chun a chumasú.",
        "PREVIEW": "Réamhamharc",
        "SHOW_IMAGE_ANYWAY": "Taispeáin íomha ar aon nós",
        "X_OF_Y": "{0} / {1}"
    },
    "__he": {
        "ACCESSIBILITY": "נגישות",
        "ACCESSIBILITY_INFORMATION_NOT_AVAILABLE": "מידע על נגישות אינו זמין",
        "ACCESSIBILITY_SCORE_HIGH": "ניקוד נגישות: גבוה",
        "ACCESSIBILITY_SCORE_LOW": "ניקוד נגישות: נמוך",
        "ACCESSIBILITY_SCORE_MEDIUM": "ניקוד נגישות: בינוני",
        "ACCESSIBILITY_SCORE_PERCENT": "ניקוד נגישות: {0}",
        "ACCESSIBILITY_SCORE_PERFECT": "ניקוד נגישות: מושלם",
        "ACTIONS": "פעולות",
        "ALTERNATIVE_FORMATS": "תבניות חלופיות",
        "ATTO_BLOCK_QUOTED": "מצוטט",
        "ATTO_BLOCK_HEADING_1": "כותרת 1",
        "ATTO_BLOCK_HEADING_2": "כותרת 2",
        "ATTO_BLOCK_HEADING_3": "כותרת 3",
        "ATTO_BLOCK_PLAIN": "רגיל",
        "ATTO_BLOCK_PRE": "לפני עיצוב",
        "CANCEL": "ביטול",
        "CLICK_TO_IMPROVE": "בחר כדי לשפר",
        "DOWNLOAD": "הורד",
        "DOWNLOAD_ALTERNATIVE_FORMATS_ELLIPSIS": "הורד תבניות חלופיות...",
        "DOWNLOAD_OPTIONS": "אפשרויות הורדה",
        "FILENAME_ALTERNATIVE_FORMAT": "{FILENAME} - תבניות חלופיות",
        "FILE_HAS_BEEN_DELETED": "הקובץ נמחק",
        "FILE_TYPE_DOCUMENT": "מסמך",
        "FILE_TYPE_HTML_PAGE": "קובץ HTML",
        "FILE_TYPE_IMAGE": "תמונה",
        "FILE_TYPE_OTHER": "אחר",
        "FILE_TYPE_PDF": "מסמך PDF",
        "FILE_TYPE_PRESENTATION": "מצגת",
        "FILE_TYPE_SCORE": "{0} -‏ {1}",
        "FIX": "תקין",
        "INSTRUCTOR_FEEDBACK": "משוב מהמרצה",
        "INSTRUCTOR_FEEDBACK_FOR": "משוב מהמרצה עבור {0}",
        "LOADING_INSTRUCTOR_FEEDBACK_PLEASE_WAIT": "טוען משוב מהמרצה. נא המתן.",
        "POTENTIALLY_SEIZURE_INDUCING": "עלול לגרום להתקפים",
        "POTENTIALLY_SEIZURE_INDUCING_ANIMATION_PRESS_TO_ENABLE": "הנפשה שעלולה לגרום להתקפים. הקש כדי להפעיל.",
        "PREVIEW": "תצוגה מקדימה",
        "SHOW_IMAGE_ANYWAY": "הצג את התמונה בכל זאת",
        "X_OF_Y": "{0} / {1}"
    },
    "__it": {
        "ACCESSIBILITY": "Accessibilità",
        "ACCESSIBILITY_INFORMATION_NOT_AVAILABLE": "Informazioni sull'accessibilità non disponibili",
        "ACCESSIBILITY_SCORE_HIGH": "Punteggio di accessibilità: alto",
        "ACCESSIBILITY_SCORE_LOW": "Punteggio di accessibilità: basso",
        "ACCESSIBILITY_SCORE_MEDIUM": "Punteggio di accessibilità: medio",
        "ACCESSIBILITY_SCORE_PERCENT": "Punteggio di accessibilità: {0}",
        "ACCESSIBILITY_SCORE_PERFECT": "Punteggio di accessibilità: perfetto",
        "ACTIONS": "Azioni",
        "ALTERNATIVE_FORMATS": "Formati alternativi",
        "ATTO_BLOCK_QUOTED": "Citato",
        "ATTO_BLOCK_HEADING_1": "Intestazione 1",
        "ATTO_BLOCK_HEADING_2": "Intestazione 2",
        "ATTO_BLOCK_HEADING_3": "Intestazione 3",
        "ATTO_BLOCK_PLAIN": "Normale",
        "ATTO_BLOCK_PRE": "Preformattato",
        "CANCEL": "Annulla",
        "CLICK_TO_IMPROVE": "Selezionare per migliorare",
        "DOWNLOAD": "Scarica",
        "DOWNLOAD_ALTERNATIVE_FORMATS_ELLIPSIS": "Scarica formati alternativi ...",
        "DOWNLOAD_OPTIONS": "Opzioni di download",
        "FILENAME_ALTERNATIVE_FORMAT": "{FILENAME} - Formati alternativi",
        "FILE_HAS_BEEN_DELETED": "Il file è stato eliminato",
        "FILE_TYPE_DOCUMENT": "Documento",
        "FILE_TYPE_HTML_PAGE": "File HTML",
        "FILE_TYPE_IMAGE": "Immagine",
        "FILE_TYPE_OTHER": "Altro",
        "FILE_TYPE_PDF": "Documento PDF",
        "FILE_TYPE_PRESENTATION": "Presentazione",
        "FILE_TYPE_SCORE": "{0} - {1}",
        "FIX": "Correggi",
        "INSTRUCTOR_FEEDBACK": "Feedback docenti",
        "INSTRUCTOR_FEEDBACK_FOR": "Feedback docenti per {0}",
        "LOADING_INSTRUCTOR_FEEDBACK_PLEASE_WAIT": "Caricamento feedback docenti. Attendere.",
        "POTENTIALLY_SEIZURE_INDUCING": "Che può provocare una crisi convulsiva",
        "POTENTIALLY_SEIZURE_INDUCING_ANIMATION_PRESS_TO_ENABLE": "Animazione che può provocare una crisi convulsiva. Premere per abilitare.",
        "PREVIEW": "Anteprima",
        "SHOW_IMAGE_ANYWAY": "Mostra immagine comunque",
        "X_OF_Y": "{0} / {1}"
    },
    "__mi": {
        "ACCESSIBILITY": "Whakatapoko",
        "ACCESSIBILITY_INFORMATION_NOT_AVAILABLE": "Tē wātea ngā mōhiohio whakatapoko",
        "ACCESSIBILITY_SCORE_HIGH": "Whiwhinga whakatapoko: Teitei",
        "ACCESSIBILITY_SCORE_LOW": "Whiwhinga whakatapoko: Iti",
        "ACCESSIBILITY_SCORE_MEDIUM": "Whiwhinga whakatapoko: Waenga",
        "ACCESSIBILITY_SCORE_PERCENT": "Whiwhinga whakatapoko: {0}",
        "ACCESSIBILITY_SCORE_PERFECT": "Whiwhinga whakatapoko: Rawe",
        "ACTIONS": "Ngā Mahi",
        "ALTERNATIVE_FORMATS": "Ngā Hōputu Kē",
        "ATTO_BLOCK_QUOTED": "I kīia",
        "ATTO_BLOCK_HEADING_1": "Upoko 1",
        "ATTO_BLOCK_HEADING_2": "Upoko 2",
        "ATTO_BLOCK_HEADING_3": "Upoko 3",
        "ATTO_BLOCK_PLAIN": "Tōkau",
        "ATTO_BLOCK_PRE": "I whakahōputu tōmuatia",
        "CANCEL": "Whakakore",
        "CLICK_TO_IMPROVE": "Tīpako ki te whakapai ake",
        "DOWNLOAD": "Tikiake",
        "DOWNLOAD_ALTERNATIVE_FORMATS_ELLIPSIS": "Tikiake hōputu kē ...",
        "DOWNLOAD_OPTIONS": "Tikiake kōwhiringa",
        "FILENAME_ALTERNATIVE_FORMAT": "{FILENAME} - Ngā Hōputu Kē",
        "FILE_HAS_BEEN_DELETED": "Kua mukua te kōnae",
        "FILE_TYPE_DOCUMENT": "Tuhinga",
        "FILE_TYPE_HTML_PAGE": "Kōnae HTML",
        "FILE_TYPE_IMAGE": "Atahanga",
        "FILE_TYPE_OTHER": "Ētahi atu",
        "FILE_TYPE_PDF": "Tuhinga PDF",
        "FILE_TYPE_PRESENTATION": "Whakaaturanga",
        "FILE_TYPE_SCORE": "{0} - {1}",
        "FIX": "Whakatika",
        "INSTRUCTOR_FEEDBACK": "Urupare kaitohutohu",
        "INSTRUCTOR_FEEDBACK_FOR": "Urupare kaitohutohu mō {0}",
        "LOADING_INSTRUCTOR_FEEDBACK_PLEASE_WAIT": "Uta Urupare Kaitohutohu Ana. Taihoa.",
        "POTENTIALLY_SEIZURE_INDUCING": "Ka whakahūkeke pea",
        "POTENTIALLY_SEIZURE_INDUCING_ANIMATION_PRESS_TO_ENABLE": "Hākoritanga ka whakahūkeke pea. Pēhi ki te whakahohe.",
        "PREVIEW": "Tiro takamua",
        "SHOW_IMAGE_ANYWAY": "Whakaatu atahanga ahakoa te aha",
        "X_OF_Y": "{0} / {1}"
    },
    "__nb": {
        "ACCESSIBILITY": "Tilgjengelighet",
        "ACCESSIBILITY_INFORMATION_NOT_AVAILABLE": "Ingen tilgjengelighetsinformasjon er tilgjengelig",
        "ACCESSIBILITY_SCORE_HIGH": "Tilgjengelighetsresultat: God",
        "ACCESSIBILITY_SCORE_LOW": "Tilgjengelighetsresultat: Dårlig",
        "ACCESSIBILITY_SCORE_MEDIUM": "Tilgjengelighetsresultat: Middels",
        "ACCESSIBILITY_SCORE_PERCENT": "Tilgjengelighetsresultat: {0}",
        "ACCESSIBILITY_SCORE_PERFECT": "Tilgjengelighetsresultat: Perfekt",
        "ACTIONS": "Handlinger",
        "ALTERNATIVE_FORMATS": "Alternative formater",
        "ATTO_BLOCK_QUOTED": "Sitert",
        "ATTO_BLOCK_HEADING_1": "Overskrift 1",
        "ATTO_BLOCK_HEADING_2": "Overskrift 2",
        "ATTO_BLOCK_HEADING_3": "Overskrift 3",
        "ATTO_BLOCK_PLAIN": "Ren",
        "ATTO_BLOCK_PRE": "Forhåndsformatert",
        "CANCEL": "Avbryt",
        "CLICK_TO_IMPROVE": "Velg for å forbedre",
        "DOWNLOAD": "Last ned",
        "DOWNLOAD_ALTERNATIVE_FORMATS_ELLIPSIS": "Last ned alternative formater ...",
        "DOWNLOAD_OPTIONS": "Nedlastingsalternativer",
        "FILENAME_ALTERNATIVE_FORMAT": "{FILENAME} – alternative formater",
        "FILE_HAS_BEEN_DELETED": "Filen er slettet",
        "FILE_TYPE_DOCUMENT": "Dokument",
        "FILE_TYPE_HTML_PAGE": "HTML-fil",
        "FILE_TYPE_IMAGE": "Bilde",
        "FILE_TYPE_OTHER": "Annet",
        "FILE_TYPE_PDF": "Rediger dokumentet",
        "FILE_TYPE_PRESENTATION": "Presentasjon",
        "FILE_TYPE_SCORE": "{0}–{1}",
        "FIX": "Fiks",
        "INSTRUCTOR_FEEDBACK": "Tilbakemelding fra underviseren",
        "INSTRUCTOR_FEEDBACK_FOR": "Undervisertilbakemelding for {0}",
        "LOADING_INSTRUCTOR_FEEDBACK_PLEASE_WAIT": "Laster inn tilbakemelding fra underviseren. Vent litt.",
        "POTENTIALLY_SEIZURE_INDUCING": "Potensielt anfallsfremkallende",
        "POTENTIALLY_SEIZURE_INDUCING_ANIMATION_PRESS_TO_ENABLE": "Potensielt anfallsfremkallende animasjon. Trykk for å aktivere den.",
        "PREVIEW": "Forhåndsvisning",
        "SHOW_IMAGE_ANYWAY": "Vis bildet likevel",
        "X_OF_Y": "{0} / {1}"
    },
    "__nn": {
        "ACCESSIBILITY": "Tilgjenge",
        "ACCESSIBILITY_INFORMATION_NOT_AVAILABLE": "Tilgjengeinformasjon ikkje tilgjengeleg",
        "ACCESSIBILITY_SCORE_HIGH": "Tilgjengevurdering: Høg",
        "ACCESSIBILITY_SCORE_LOW": "Tilgjengevurdering: Låg",
        "ACCESSIBILITY_SCORE_MEDIUM": "Tilgjengevurdering: Middels",
        "ACCESSIBILITY_SCORE_PERFECT": "Tilgjengevurdering: Perfekt",
        "ALTERNATIVE_FORMATS": "Alternative format",
        "CANCEL": "Avbryt",
        "CLICK_TO_IMPROVE": "Klikk for å betre",
        "DOWNLOAD": "Last ned",
        "DOWNLOAD_OPTIONS": "Last ned alternativ",
        "FILE_HAS_BEEN_DELETED": "Fila er sletta",
        "FILE_TYPE_DOCUMENT": "Dokument",
        "FILE_TYPE_HTML_PAGE": "HTML-fil",
        "FILE_TYPE_IMAGE": "Bilete",
        "FILE_TYPE_OTHER": "Anna",
        "FILE_TYPE_PDF": "PDF-dokument",
        "FILE_TYPE_PRESENTATION": "Presentasjon",
        "FILE_TYPE_SCORE": "{0}−{1}",
        "FIX": "Reparer",
        "INSTRUCTOR_FEEDBACK": "Tilbakemelding frå lærar",
        "LOADING_INSTRUCTOR_FEEDBACK_PLEASE_WAIT": "Lastar inn tilbakemelding frå lærar. Vent litt.",
        "POTENTIALLY_SEIZURE_INDUCING": "Potensielt åtaksframkallande",
        "POTENTIALLY_SEIZURE_INDUCING_ANIMATION_PRESS_TO_ENABLE": "Potensielt åtaksframkallande animasjon. Trykk for å aktivere.",
        "PREVIEW": "Førehandsvis",
        "SHOW_IMAGE_ANYWAY": "Vis bilete likevel"
    },
    "__nn-no": {
        "ACCESSIBILITY": "Tilgjenge",
        "ACCESSIBILITY_INFORMATION_NOT_AVAILABLE": "Tilgjengeinformasjon ikkje tilgjengeleg",
        "ACCESSIBILITY_SCORE_HIGH": "Tilgjengevurdering: Høg",
        "ACCESSIBILITY_SCORE_LOW": "Tilgjengevurdering: Låg",
        "ACCESSIBILITY_SCORE_MEDIUM": "Tilgjengevurdering: Middels",
        "ACCESSIBILITY_SCORE_PERCENT": "Tilgjengevurdering: {0}",
        "ACCESSIBILITY_SCORE_PERFECT": "Tilgjengevurdering: Perfekt",
        "ACTIONS": "Handlingar",
        "ALTERNATIVE_FORMATS": "Alternative format",
        "ATTO_BLOCK_QUOTED": "Mellom hermeteikn",
        "ATTO_BLOCK_HEADING_1": "Overskrift 1",
        "ATTO_BLOCK_HEADING_2": "Overskrift 2",
        "ATTO_BLOCK_HEADING_3": "Overskrift 3",
        "ATTO_BLOCK_PLAIN": "Rein",
        "ATTO_BLOCK_PRE": "Førehandsformatert",
        "CANCEL": "Avbryt",
        "CLICK_TO_IMPROVE": "Vel for å betre",
        "DOWNLOAD": "Last ned",
        "DOWNLOAD_ALTERNATIVE_FORMATS_ELLIPSIS": "Last ned alternative format ...",
        "DOWNLOAD_OPTIONS": "Last ned alternativ",
        "FILENAME_ALTERNATIVE_FORMAT": "{FILENAME} - Alternative format",
        "FILE_HAS_BEEN_DELETED": "Fila er sletta",
        "FILE_TYPE_DOCUMENT": "Dokument",
        "FILE_TYPE_HTML_PAGE": "HTML-fil",
        "FILE_TYPE_IMAGE": "Bilete",
        "FILE_TYPE_OTHER": "Anna",
        "FILE_TYPE_PDF": "PDF-dokument",
        "FILE_TYPE_PRESENTATION": "Presentasjon",
        "FILE_TYPE_SCORE": "{0}−{1}",
        "FIX": "Reparer",
        "INSTRUCTOR_FEEDBACK": "Tilbakemelding frå lærar",
        "INSTRUCTOR_FEEDBACK_FOR": "Lærartilbakemelding for {0}",
        "LOADING_INSTRUCTOR_FEEDBACK_PLEASE_WAIT": "Lastar inn tilbakemelding frå lærar. Vent litt.",
        "POTENTIALLY_SEIZURE_INDUCING": "Potensielt åtaksframkallande",
        "POTENTIALLY_SEIZURE_INDUCING_ANIMATION_PRESS_TO_ENABLE": "Potensielt åtaksframkallande animasjon. Trykk for å aktivere.",
        "PREVIEW": "Førehandsvis",
        "SHOW_IMAGE_ANYWAY": "Vis bilde likevel",
        "X_OF_Y": "{0} / {1}"
    },
    "__nl": {
        "ACCESSIBILITY": "Toegankelijkheid",
        "ACCESSIBILITY_INFORMATION_NOT_AVAILABLE": "Toegankelijkheidsinformatie is niet beschikbaar",
        "ACCESSIBILITY_SCORE_HIGH": "Toegankelijkheidsscore: hoog",
        "ACCESSIBILITY_SCORE_LOW": "Toegankelijkheidsscore: laag",
        "ACCESSIBILITY_SCORE_MEDIUM": "Toegankelijkheidsscore: gemiddeld",
        "ACCESSIBILITY_SCORE_PERCENT": "Toegankelijkheidsscore: {0}",
        "ACCESSIBILITY_SCORE_PERFECT": "Toegankelijkheidsscore: perfect",
        "ACTIONS": "Acties",
        "ALTERNATIVE_FORMATS": "Alternatieve formaten",
        "ATTO_BLOCK_QUOTED": "Geciteerd",
        "ATTO_BLOCK_HEADING_1": "Kop 1",
        "ATTO_BLOCK_HEADING_2": "Kop 2",
        "ATTO_BLOCK_HEADING_3": "Kop 3",
        "ATTO_BLOCK_PLAIN": "Zonder opmaak",
        "ATTO_BLOCK_PRE": "Voorgeformatteerd",
        "CANCEL": "Annuleren",
        "CLICK_TO_IMPROVE": "Selecteren om te verbeteren",
        "DOWNLOAD": "Downloaden",
        "DOWNLOAD_ALTERNATIVE_FORMATS_ELLIPSIS": "Alternatieve formaten downloaden ...",
        "DOWNLOAD_OPTIONS": "Downloadopties",
        "FILENAME_ALTERNATIVE_FORMAT": "{FILENAME} - Alternatieve formaten",
        "FILE_HAS_BEEN_DELETED": "Bestand is verwijderd",
        "FILE_TYPE_DOCUMENT": "Document",
        "FILE_TYPE_HTML_PAGE": "HTML-bestand",
        "FILE_TYPE_IMAGE": "Afbeelding",
        "FILE_TYPE_OTHER": "Overige",
        "FILE_TYPE_PDF": "PDF-document",
        "FILE_TYPE_PRESENTATION": "Presentatie",
        "FILE_TYPE_SCORE": "{0} - {1}",
        "FIX": "Corrigeren",
        "INSTRUCTOR_FEEDBACK": "Feedback cursusleider",
        "INSTRUCTOR_FEEDBACK_FOR": "Feedback cursusleider voor {0}",
        "LOADING_INSTRUCTOR_FEEDBACK_PLEASE_WAIT": "De feedback van de cursusleider wordt geladen, even geduld aub.",
        "POTENTIALLY_SEIZURE_INDUCING": "Potentiële aanval opwekkende",
        "POTENTIALLY_SEIZURE_INDUCING_ANIMATION_PRESS_TO_ENABLE": "Potentiële aanval opwekkende animatie. Klik om in te schakelen.",
        "PREVIEW": "Voorbeeld",
        "SHOW_IMAGE_ANYWAY": "Afbeelding toch tonen",
        "X_OF_Y": "{0} / {1}"
    },
    "__pl": {
        "ACCESSIBILITY": "Ułatwienia dostępu",
        "ACCESSIBILITY_INFORMATION_NOT_AVAILABLE": "Informacje o ułatwieniach dostępu są niedostępne",
        "ACCESSIBILITY_SCORE_HIGH": "Ocena dostępności: wysoka",
        "ACCESSIBILITY_SCORE_LOW": "Ocena dostępności: niska",
        "ACCESSIBILITY_SCORE_MEDIUM": "Ocena dostępności: przeciętna",
        "ACCESSIBILITY_SCORE_PERCENT": "Ocena dostępności: {0}",
        "ACCESSIBILITY_SCORE_PERFECT": "Ocena dostępności: doskonała",
        "ACTIONS": "Działania",
        "ALTERNATIVE_FORMATS": "Alternatywne formaty",
        "ATTO_BLOCK_QUOTED": "Cytat",
        "ATTO_BLOCK_HEADING_1": "Nagłówek 1",
        "ATTO_BLOCK_HEADING_2": "Nagłówek 2",
        "ATTO_BLOCK_HEADING_3": "Nagłówek 3",
        "ATTO_BLOCK_PLAIN": "Prosty",
        "ATTO_BLOCK_PRE": "Wstępnie sformatowany",
        "CANCEL": "Anuluj",
        "CLICK_TO_IMPROVE": "Wybierz, aby poprawić",
        "DOWNLOAD": "Pobierz",
        "DOWNLOAD_ALTERNATIVE_FORMATS_ELLIPSIS": "Pobierz alternatywne formaty...",
        "DOWNLOAD_OPTIONS": "Opcje pobierania",
        "FILENAME_ALTERNATIVE_FORMAT": "{FILENAME} – alternatywne formaty",
        "FILE_HAS_BEEN_DELETED": "Plik został usunięty",
        "FILE_TYPE_DOCUMENT": "Dokument",
        "FILE_TYPE_HTML_PAGE": "Plik HTML",
        "FILE_TYPE_IMAGE": "Obraz",
        "FILE_TYPE_OTHER": "Inne",
        "FILE_TYPE_PDF": "Dokument PDF",
        "FILE_TYPE_PRESENTATION": "Prezentacja",
        "FILE_TYPE_SCORE": "{0} — {1}",
        "FIX": "Napraw",
        "INSTRUCTOR_FEEDBACK": "Uwagi od instruktora",
        "INSTRUCTOR_FEEDBACK_FOR": "Uwagi od instruktora dla: {0}",
        "LOADING_INSTRUCTOR_FEEDBACK_PLEASE_WAIT": "Ładowanie uwag od instruktora. Proszę czekać.",
        "POTENTIALLY_SEIZURE_INDUCING": "Może wywoływać napady padaczkowe",
        "POTENTIALLY_SEIZURE_INDUCING_ANIMATION_PRESS_TO_ENABLE": "Animacja, która może wywoływać napady padaczkowe. Naciśnij, aby włączyć.",
        "PREVIEW": "Podgląd",
        "SHOW_IMAGE_ANYWAY": "Pokaż obraz mimo to",
        "X_OF_Y": "{0} / {1}"
    },
    "__pt": {
        "ACCESSIBILITY": "Acessibilidade",
        "ACCESSIBILITY_INFORMATION_NOT_AVAILABLE": "Informação de acessibilidade não disponível",
        "ACCESSIBILITY_SCORE_HIGH": "Classificação de acessibilidade: Elevada",
        "ACCESSIBILITY_SCORE_LOW": "Classificação de acessibilidade: Reduzida",
        "ACCESSIBILITY_SCORE_MEDIUM": "Classificação de acessibilidade: Média",
        "ACCESSIBILITY_SCORE_PERCENT": "Classificação de acessibilidade: {0}",
        "ACCESSIBILITY_SCORE_PERFECT": "Classificação de acessibilidade: Perfeita",
        "ACTIONS": "Ações",
        "ALTERNATIVE_FORMATS": "Formatos alternativos",
        "ATTO_BLOCK_QUOTED": "Entre aspas",
        "ATTO_BLOCK_HEADING_1": "Título 1",
        "ATTO_BLOCK_HEADING_2": "Título 2",
        "ATTO_BLOCK_HEADING_3": "Título 3",
        "ATTO_BLOCK_PLAIN": "Simples",
        "ATTO_BLOCK_PRE": "Pré-formatado",
        "CANCEL": "Cancelar",
        "CLICK_TO_IMPROVE": "Selecione para melhorar",
        "DOWNLOAD": "Transferir",
        "DOWNLOAD_ALTERNATIVE_FORMATS_ELLIPSIS": "Transferir formatos alternativos ...",
        "DOWNLOAD_OPTIONS": "Opções de transferência",
        "FILENAME_ALTERNATIVE_FORMAT": "{FILENAME} - Formatos alternativos",
        "FILE_HAS_BEEN_DELETED": "O ficheiro foi eliminado",
        "FILE_TYPE_DOCUMENT": "Documento",
        "FILE_TYPE_HTML_PAGE": "Ficheiro HTML",
        "FILE_TYPE_IMAGE": "Imagem",
        "FILE_TYPE_OTHER": "Outro",
        "FILE_TYPE_PDF": "Documento PDF",
        "FILE_TYPE_PRESENTATION": "Apresentação",
        "FILE_TYPE_SCORE": "{0} - {1}",
        "FIX": "Corrigir",
        "INSTRUCTOR_FEEDBACK": "Comentários do formador",
        "INSTRUCTOR_FEEDBACK_FOR": "Comentários do formador para {0}",
        "LOADING_INSTRUCTOR_FEEDBACK_PLEASE_WAIT": "A carregar os comentários do formador. Aguarde um momento.",
        "POTENTIALLY_SEIZURE_INDUCING": "Potencialmente indutor de convulsões",
        "POTENTIALLY_SEIZURE_INDUCING_ANIMATION_PRESS_TO_ENABLE": "Animação potencialmente indutora de convulsões. Prima para ativar.",
        "PREVIEW": "Pré-visualizar",
        "SHOW_IMAGE_ANYWAY": "Mostrar imagem mesmo assim",
        "X_OF_Y": "{0} / {1}"
    },
    "__pt-br": {
        "ACCESSIBILITY": "Acessibilidade",
        "ACCESSIBILITY_INFORMATION_NOT_AVAILABLE": "Não há informações de acessibilidade disponíveis",
        "ACCESSIBILITY_SCORE_HIGH": "Pontuação de acessibilidade: alta",
        "ACCESSIBILITY_SCORE_LOW": "Pontuação de acessibilidade: baixa",
        "ACCESSIBILITY_SCORE_MEDIUM": "Pontuação de acessibilidade: média",
        "ACCESSIBILITY_SCORE_PERCENT": "Pontuação de acessibilidade: {0}",
        "ACCESSIBILITY_SCORE_PERFECT": "Pontuação de acessibilidade: perfeita",
        "ACTIONS": "Ações",
        "ALTERNATIVE_FORMATS": "Formatos alternativos",
        "ATTO_BLOCK_QUOTED": "Citado",
        "ATTO_BLOCK_HEADING_1": "Cabeçalho 1",
        "ATTO_BLOCK_HEADING_2": "Cabeçalho 2",
        "ATTO_BLOCK_HEADING_3": "Título 3",
        "ATTO_BLOCK_PLAIN": "Sem formatação",
        "ATTO_BLOCK_PRE": "Pré-formatado",
        "CANCEL": "Cancelar",
        "CLICK_TO_IMPROVE": "Selecione para melhorar",
        "DOWNLOAD": "Fazer download",
        "DOWNLOAD_ALTERNATIVE_FORMATS_ELLIPSIS": "Baixar formatos alternativos...",
        "DOWNLOAD_OPTIONS": "Opções de download",
        "FILENAME_ALTERNATIVE_FORMAT": "{FILENAME} – Formatos alternativos",
        "FILE_HAS_BEEN_DELETED": "O arquivo foi excluído",
        "FILE_TYPE_DOCUMENT": "Documento",
        "FILE_TYPE_HTML_PAGE": "Arquivo HTML",
        "FILE_TYPE_IMAGE": "Imagem",
        "FILE_TYPE_OTHER": "Outro",
        "FILE_TYPE_PDF": "Documento PDF",
        "FILE_TYPE_PRESENTATION": "Apresentação",
        "FILE_TYPE_SCORE": "{0} - {1}",
        "FIX": "Corrigir",
        "INSTRUCTOR_FEEDBACK": "Comentários do instrutor",
        "INSTRUCTOR_FEEDBACK_FOR": "Comentários do instrutor para {0}",
        "LOADING_INSTRUCTOR_FEEDBACK_PLEASE_WAIT": "Carregando os comentários do instrutor. Aguarde.",
        "POTENTIALLY_SEIZURE_INDUCING": "Possibilidade de provocar convulsão",
        "POTENTIALLY_SEIZURE_INDUCING_ANIMATION_PRESS_TO_ENABLE": "Animação com possibilidade de provocar convulsão. Pressione para habilitar.",
        "PREVIEW": "Pré-visualização",
        "SHOW_IMAGE_ANYWAY": "Mostrar imagem mesmo assim",
        "X_OF_Y": "{0}/{1}"
    },
    "__sv": {
        "ACCESSIBILITY": "Tillgänglighet",
        "ACCESSIBILITY_INFORMATION_NOT_AVAILABLE": "Tillgänglighetsinformation är inte tillgänglig",
        "ACCESSIBILITY_SCORE_HIGH": "Tillgänglighetspoäng: hög",
        "ACCESSIBILITY_SCORE_LOW": "Tillgänglighetspoäng: låg",
        "ACCESSIBILITY_SCORE_MEDIUM": "Tillgänglighetspoäng: mellan",
        "ACCESSIBILITY_SCORE_PERCENT": "Tillgänglighetspoäng: {0}",
        "ACCESSIBILITY_SCORE_PERFECT": "Tillgänglighetspoäng: perfekt",
        "ACTIONS": "Åtgärder",
        "ALTERNATIVE_FORMATS": "Alternativa format",
        "ATTO_BLOCK_QUOTED": "Citat",
        "ATTO_BLOCK_HEADING_1": "Rubrik 1",
        "ATTO_BLOCK_HEADING_2": "Rubrik 2",
        "ATTO_BLOCK_HEADING_3": "Rubrik 3",
        "ATTO_BLOCK_PLAIN": "Oformaterat",
        "ATTO_BLOCK_PRE": "Förformaterat",
        "CANCEL": "Avbryt",
        "CLICK_TO_IMPROVE": "Välj för att förbättra",
        "DOWNLOAD": "Ladda ner",
        "DOWNLOAD_ALTERNATIVE_FORMATS_ELLIPSIS": "Ladda ner alternativa format ...",
        "DOWNLOAD_OPTIONS": "Nerladdningsalternativ",
        "FILENAME_ALTERNATIVE_FORMAT": "{FILENAME} – Alternativa format",
        "FILE_HAS_BEEN_DELETED": "Filen har raderats",
        "FILE_TYPE_DOCUMENT": "Dokument",
        "FILE_TYPE_HTML_PAGE": "HTML-fil",
        "FILE_TYPE_IMAGE": "Bild",
        "FILE_TYPE_OTHER": "Annat",
        "FILE_TYPE_PDF": "PDF-dokument",
        "FILE_TYPE_PRESENTATION": "Presentation",
        "FILE_TYPE_SCORE": "{0}–{1}",
        "FIX": "Fixa",
        "INSTRUCTOR_FEEDBACK": "Läraråterkoppling",
        "INSTRUCTOR_FEEDBACK_FOR": "Läraråterkoppling för {0}",
        "LOADING_INSTRUCTOR_FEEDBACK_PLEASE_WAIT": "Laddar läraråterkoppling. Vänta.",
        "POTENTIALLY_SEIZURE_INDUCING": "Kan potentiellt framkalla anfall",
        "POTENTIALLY_SEIZURE_INDUCING_ANIMATION_PRESS_TO_ENABLE": "Animation som potentiellt kan framkalla anfall. Klicka för att aktivera.",
        "PREVIEW": "Förhandsvisning",
        "SHOW_IMAGE_ANYWAY": "Visa bilden ändå",
        "X_OF_Y": "{0}/{1}"
    },
    "__tr": {
        "ACCESSIBILITY": "Erişilebilirlik",
        "ACCESSIBILITY_INFORMATION_NOT_AVAILABLE": "Erişilebilirlik bilgileri kullanılamıyor",
        "ACCESSIBILITY_SCORE_HIGH": "Erişilebilirlik puanı: Yüksek",
        "ACCESSIBILITY_SCORE_LOW": "Erişilebilirlik puanı: Düşük",
        "ACCESSIBILITY_SCORE_MEDIUM": "Erişilebilirlik puanı: Orta",
        "ACCESSIBILITY_SCORE_PERCENT": "Erişilebilirlik puanı: {0}",
        "ACCESSIBILITY_SCORE_PERFECT": "Erişilebilirlik puanı: Mükemmel",
        "ACTIONS": "Eylemler",
        "ALTERNATIVE_FORMATS": "Alternatif biçimler",
        "ATTO_BLOCK_QUOTED": "Alıntı Yapılmış",
        "ATTO_BLOCK_HEADING_1": "Başlık 1",
        "ATTO_BLOCK_HEADING_2": "Başlık 2",
        "ATTO_BLOCK_HEADING_3": "Başlık 3",
        "ATTO_BLOCK_PLAIN": "Düz",
        "ATTO_BLOCK_PRE": "Önceden Biçimlendirilmiş",
        "CANCEL": "İptal",
        "CLICK_TO_IMPROVE": "İyileştirmek için seçin",
        "DOWNLOAD": "İndir",
        "DOWNLOAD_ALTERNATIVE_FORMATS_ELLIPSIS": "Alternatif biçimleri indirin...",
        "DOWNLOAD_OPTIONS": "İndirme seçenekleri",
        "FILENAME_ALTERNATIVE_FORMAT": "{FILENAME} - Alternatif Biçimler",
        "FILE_HAS_BEEN_DELETED": "Dosya silindi",
        "FILE_TYPE_DOCUMENT": "Belge",
        "FILE_TYPE_HTML_PAGE": "HTML dosyası",
        "FILE_TYPE_IMAGE": "Görüntü",
        "FILE_TYPE_OTHER": "Diğer",
        "FILE_TYPE_PDF": "PDF belgesi",
        "FILE_TYPE_PRESENTATION": "Sunum",
        "FILE_TYPE_SCORE": "{0} - {1}",
        "FIX": "Düzelt",
        "INSTRUCTOR_FEEDBACK": "Eğitmen geri bildirimi",
        "INSTRUCTOR_FEEDBACK_FOR": "{0} için eğitmen geri bildirimi",
        "LOADING_INSTRUCTOR_FEEDBACK_PLEASE_WAIT": "Eğitmen Geri Bildirimi yükleniyor. Lütfen bekleyin.",
        "POTENTIALLY_SEIZURE_INDUCING": "Nöbete yol açabilir",
        "POTENTIALLY_SEIZURE_INDUCING_ANIMATION_PRESS_TO_ENABLE": "Nöbete yol açabilecek animasyon. Etkinleştirmek için basın.",
        "PREVIEW": "Ön izleme",
        "SHOW_IMAGE_ANYWAY": "Görüntüyü yine de göster",
        "X_OF_Y": "{0}/{1}"
    },
    "__xh_ZA": {
        "ACCESSIBILITY": "Ukufikeleleka",
        "ACCESSIBILITY_INFORMATION_NOT_AVAILABLE": "Inkcazelo yofikeleleko ayikho",
        "ACCESSIBILITY_SCORE_HIGH": "Inqaku lofikeleleko: Liphezulu",
        "ACCESSIBILITY_SCORE_LOW": "Inqaku lofikeleleko: Lisezantsi",
        "ACCESSIBILITY_SCORE_MEDIUM": "Inqaku lofikeleleko: Liphakathi",
        "ACCESSIBILITY_SCORE_PERCENT": "Inqaku lofikeleleko: {0}",
        "ACCESSIBILITY_SCORE_PERFECT": "Inqaku lofikeleleko: Ligqibelele",
        "ACTIONS": "Izenzo",
        "ALTERNATIVE_FORMATS": "Ezinye iifomathi",
        "ATTO_BLOCK_QUOTED": "Ezicatshuliweyo",
        "ATTO_BLOCK_HEADING_1": "Umxholo 1",
        "ATTO_BLOCK_HEADING_2": "Umxholo 2",
        "ATTO_BLOCK_HEADING_3": "Umxholo 3",
        "ATTO_BLOCK_PLAIN": "Epleyini",
        "ATTO_BLOCK_PRE": "Efomathwe kwangaphambili",
        "CANCEL": "Rhoxisa",
        "CLICK_TO_IMPROVE": "Khetha ukuze uphucule",
        "DOWNLOAD": "Dawnlowuda",
        "DOWNLOAD_ALTERNATIVE_FORMATS_ELLIPSIS": "Dawnlowuda ezinye iifomathi ...",
        "DOWNLOAD_OPTIONS": "Ukhetho xa udawunlowuda",
        "FILENAME_ALTERNATIVE_FORMAT": "{FILENAME} - Ezinye Iifomathi",
        "FILE_HAS_BEEN_DELETED": "Ifayile iye yacinywa",
        "FILE_TYPE_DOCUMENT": "Uxwebhu",
        "FILE_TYPE_HTML_PAGE": "Ifayile yeHTML",
        "FILE_TYPE_IMAGE": "Umfanekiso",
        "FILE_TYPE_OTHER": "Ezinye",
        "FILE_TYPE_PDF": "Uxwebhu lwePDF",
        "FILE_TYPE_PRESENTATION": "Iprizenteyishini",
        "FILE_TYPE_SCORE": "{0} - {1}",
        "FIX": "Lungisa",
        "INSTRUCTOR_FEEDBACK": "Uluvo lomhlohli",
        "INSTRUCTOR_FEEDBACK_FOR": "Uluvo lomhlohli ku {0}",
        "LOADING_INSTRUCTOR_FEEDBACK_PLEASE_WAIT": "Ilowuda Uluvo Lomhlohli. Nceda ulinde.",
        "POTENTIALLY_SEIZURE_INDUCING": "Inokubangela kuvuseleleke ukuxhuzula",
        "POTENTIALLY_SEIZURE_INDUCING_ANIMATION_PRESS_TO_ENABLE": "Umboniso onokubangela kuvuseleleke ukuxhuzula. Cofa ukuze uvulele.",
        "PREVIEW": "Qala uyibone",
        "SHOW_IMAGE_ANYWAY": "Wubonise umfanekiso nakubeni kunjalo",
        "X_OF_Y": "{0} / {1}"
    },
    "__zh_TW": {
        "ACCESSIBILITY": "無障礙",
        "ACCESSIBILITY_INFORMATION_NOT_AVAILABLE": "未提供無障礙資訊",
        "ACCESSIBILITY_SCORE_HIGH": "無障礙分數: 高",
        "ACCESSIBILITY_SCORE_LOW": "無障礙分數: 低",
        "ACCESSIBILITY_SCORE_MEDIUM": "無障礙分數: 中",
        "ACCESSIBILITY_SCORE_PERCENT": "無障礙分數: {0}",
        "ACCESSIBILITY_SCORE_PERFECT": "無障礙分數: 理想",
        "ACTIONS": "動作",
        "ALTERNATIVE_FORMATS": "替代格式",
        "ATTO_BLOCK_QUOTED": "加上引號",
        "ATTO_BLOCK_HEADING_1": "標題 1",
        "ATTO_BLOCK_HEADING_2": "標題 2",
        "ATTO_BLOCK_HEADING_3": "標題 3",
        "ATTO_BLOCK_PLAIN": "純文字",
        "ATTO_BLOCK_PRE": "已預先格式化",
        "CANCEL": "取消",
        "CLICK_TO_IMPROVE": "選取以改進",
        "DOWNLOAD": "下載",
        "DOWNLOAD_ALTERNATIVE_FORMATS_ELLIPSIS": "下載替代格式...",
        "DOWNLOAD_OPTIONS": "下載選項",
        "FILENAME_ALTERNATIVE_FORMAT": "{FILENAME} - 替代格式",
        "FILE_HAS_BEEN_DELETED": "已刪除檔案",
        "FILE_TYPE_DOCUMENT": "文件",
        "FILE_TYPE_HTML_PAGE": "HTML 檔案",
        "FILE_TYPE_IMAGE": "影像",
        "FILE_TYPE_OTHER": "其他",
        "FILE_TYPE_PDF": "PDF 文件",
        "FILE_TYPE_PRESENTATION": "簡報",
        "FILE_TYPE_SCORE": "{0} - {1}",
        "FIX": "修正",
        "INSTRUCTOR_FEEDBACK": "講師意見回應",
        "INSTRUCTOR_FEEDBACK_FOR": "{0} 的講師意見回應",
        "LOADING_INSTRUCTOR_FEEDBACK_PLEASE_WAIT": "正在載入講師意見回應。請稍候。",
        "POTENTIALLY_SEIZURE_INDUCING": "可能引發癲癇",
        "POTENTIALLY_SEIZURE_INDUCING_ANIMATION_PRESS_TO_ENABLE": "可能引發癲癇的動畫。按下以啟用。",
        "PREVIEW": "預覽",
        "SHOW_IMAGE_ANYWAY": "仍要顯示影像",
        "X_OF_Y": "{0} (共 {1})"
    },
    "__zu": {
        "ACCESSIBILITY": "Ukufinyeleleka",
        "ACCESSIBILITY_INFORMATION_NOT_AVAILABLE": "Imininingwane yokufinyeleleka ayitholakali",
        "ACCESSIBILITY_SCORE_HIGH": "Isko sokufinyeleleka: Siphezulu",
        "ACCESSIBILITY_SCORE_LOW": "Isko sokufinyeleleka: Siphansi",
        "ACCESSIBILITY_SCORE_MEDIUM": "Isko sokufinyeleleka: Siphakathi Nendawo",
        "ACCESSIBILITY_SCORE_PERCENT": "Isko sokufinyeleleka: {0}",
        "ACCESSIBILITY_SCORE_PERFECT": "Isko sokufinyeleleka: Sihle Kakhulu",
        "ACTIONS": "Okungenziwa",
        "ALTERNATIVE_FORMATS": "Amanye amafomethi",
        "ATTO_BLOCK_QUOTED": "Okucashuniwe",
        "ATTO_BLOCK_HEADING_1": "Isihloko 1",
        "ATTO_BLOCK_HEADING_2": "Isihloko 2",
        "ATTO_BLOCK_HEADING_3": "Isihloko 3",
        "ATTO_BLOCK_PLAIN": "Akunalutho",
        "ATTO_BLOCK_PRE": "Kufomethwe kakade",
        "CANCEL": "Khansela",
        "CLICK_TO_IMPROVE": "Khetha uthuthukise",
        "DOWNLOAD": "Dawuniloda",
        "DOWNLOAD_ALTERNATIVE_FORMATS_ELLIPSIS": "Dawuniloda amanye amafomethi ...",
        "DOWNLOAD_OPTIONS": "OngakuDawuniloda",
        "FILENAME_ALTERNATIVE_FORMAT": "{FILENAME} - Amanye Amafomethi",
        "FILE_HAS_BEEN_DELETED": "Ifayela likhishiwe",
        "FILE_TYPE_DOCUMENT": "Idokhumenti",
        "FILE_TYPE_HTML_PAGE": "Ifayela le-HTML",
        "FILE_TYPE_IMAGE": "Isithombe",
        "FILE_TYPE_OTHER": "Okunye",
        "FILE_TYPE_PDF": "Idokhumenti ye-PDF",
        "FILE_TYPE_PRESENTATION": "Iphrezenteshi",
        "FILE_TYPE_SCORE": "{0} - {1}",
        "FIX": "Lungisa",
        "INSTRUCTOR_FEEDBACK": "Okuphawulwe umfundisi",
        "INSTRUCTOR_FEEDBACK_FOR": "Okuphawulwe umfundisi nge-{0}",
        "LOADING_INSTRUCTOR_FEEDBACK_PLEASE_WAIT": "Kusalayisha Okuphawulwe Umfundisi. Sicela ulinde.",
        "POTENTIALLY_SEIZURE_INDUCING": "Ingase ivuse isifo sokuwa",
        "POTENTIALLY_SEIZURE_INDUCING_ANIMATION_PRESS_TO_ENABLE": "Opopayi bangavusa isifo sokuwa. Thinta uvule.",
        "PREVIEW": "Buyekeza",
        "SHOW_IMAGE_ANYWAY": "Veza isthombe noma kunjalo",
        "X_OF_Y": "{0} / {1}"
    }
};
amdi18n.init = function(language) {
    // get the default language
    if (!language) {
        if (window._i18n && window._i18n.locale) {
            language = window._i18n.locale;
        } else if (document.documentElement.lang) {
            language = document.documentElement.lang;
        } else {
            language = 'root';
        }
    }
    var target = this['__' + language] || this.__root;

    // copy definition to root level
    if (target) {
        for (var name in target) {
            this[name] = target[name];
        }
    }

    // fallback to root
    for (var name in this.__root) {
        if (typeof this[name] === 'undefined') {
            this[name] = this.__root[name];
        }
    }
};
amdi18n.init();
module.exports = amdi18n;